/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.openflexo.testPamela;

import org.openflexo.pamela.PamelaMetaModel;
import org.openflexo.pamela.PamelaMetaModelLibrary;
import org.openflexo.pamela.exceptions.ModelDefinitionException;
import org.openflexo.pamela.factory.PamelaModelFactory;
import org.openflexo.testPamela.model.Book;
import org.openflexo.testPamela.model.Library;

public class App {

    public Library books;

    public App() throws ModelDefinitionException {
		// Instantiate the meta-model
		// by computing the closure of concepts graph
		PamelaMetaModel pamelaMetaModel = PamelaMetaModelLibrary.retrieveMetaModel(Library.class);
		// Instantiate the factory
		PamelaModelFactory factory = new PamelaModelFactory(pamelaMetaModel);

        // Instantiate a book, the Book class has been loaded because Library depends on Book
        Book aBook = factory.newInstance(Book.class, "Lord of the ring");

        this.books = factory.newInstance(Library.class);
        this.books.addToBooks(aBook);
        System.out.println("result is " + aBook);
        if (aBook.isCorrect()) {
          System.out.println("result is correct");
        } else {
          System.out.println("result is not correct");
        }
    }

    public static void main(String[] args) throws ModelDefinitionException {
        App app = new App();
        System.out.println("library is " + app.books);
    }
}
