/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.openflexo.testPamela;

import org.junit.Test;
import static org.junit.Assert.*;
import org.openflexo.testPamela.model.Book;
import org.openflexo.pamela.exceptions.ModelDefinitionException;

public class AppTest {
    
	@Test 
    public void testLord() throws ModelDefinitionException {
        App classUnderTest = new App();
        boolean found = false;
        for (Book b : classUnderTest.books) {
            if (b.getTitle().equals("Lord of the ring")) {
                found = true;
                break;
            }
        }
        assertTrue("app should have 'Lord of the ring'", found);
    }

    @Test 
    public void testOther() throws ModelDefinitionException {
        App classUnderTest = new App();
        boolean found = false;
        for (Book b : classUnderTest.books) {
            if (b.getTitle().equals("God of the ring")) {
                found = true;
                break;
            }
        }
        assertFalse("app should not have 'God of the ring'", found);
    }
}
